SITES = [
    {
        "name": "GitHub",
        "url": "https://github.com/{}",
        "errorType": "message",
        "errorMsg": "Not Found",
    },
    {
        "name": "GitLab",
        "url": "https://gitlab.com/{}",
        "errorType": "message",
        "errorMsg": "Sorry, we can't find",
    },
    {
        "name": "Instagram",
        "url": "https://www.instagram.com/api/v1/users/web_profile_info/?username={}",
        "errorType": "json_key",
        "errorKey": "error",
        "headers_extra": {"x-ig-app-id": "936619743392459"},
    },
    {
        "name": "TikTok",
        "url": "https://www.tiktok.com/@{}",
        "errorType": "message",
        "errorMsg": "\"statusCode\":10202",
    },
    {
        "name": "Reddit",
        "url": "https://www.reddit.com/user/{}/about.json",
        "errorType": "json_key",
        "errorKey": "error",
    },
    {
        "name": "Pinterest",
        "url": "https://www.pinterest.com/{}/_saved/",
        "errorType": "message",
        "errorMsg": "couldn't find",
    },
    {
        "name": "Telegram",
        "url": "https://t.me/{}",
        "errorType": "message",
        "errorMsg": "tgme_page_description",
        "checkMode": "present",
    },
    {
        "name": "YouTube",
        "url": "https://www.youtube.com/@{}",
        "errorType": "message",
        "errorMsg": "This channel does not exist",
    },
    {
        "name": "SoundCloud",
        "url": "https://soundcloud.com/{}",
        "errorType": "message",
        "errorMsg": "We can't find that user",
    },
    {
        "name": "Twitch",
        "url": "https://www.twitch.tv/{}",
        "errorType": "message",
        "errorMsg": "isLiveBroadcast",
        "checkMode": "present",
    },
    {
        "name": "Steam",
        "url": "https://steamcommunity.com/id/{}",
        "errorType": "message",
        "errorMsg": "The specified profile could not be found.",
    },
    {
        "name": "Medium",
        "url": "https://medium.com/@{}",
        "errorType": "message",
        "errorMsg": "PageNotFound",
    },
    {
        "name": "Dev.to",
        "url": "https://dev.to/{}",
        "errorType": "message",
        "errorMsg": "404 Not Found",
    },
    {
        "name": "Replit",
        "url": "https://replit.com/@{}",
        "errorType": "message",
        "errorMsg": "not found",
    },
    {
        "name": "Twitter/X",
        "url": "https://x.com/{}",
        "errorType": "message",
        "errorMsg": "This account doesn't exist",
    },
    {
        "name": "LinkedIn",
        "url": "https://www.linkedin.com/in/{}",
        "errorType": "message",
        "errorMsg": "Page not found",
    },
    {
        "name": "Snapchat",
        "url": "https://www.snapchat.com/add/{}",
        "errorType": "message",
        "errorMsg": "Sorry, we couldn't find",
    },
    {
        "name": "Facebook",
        "url": "https://www.facebook.com/{}",
        "errorType": "message",
        "errorMsg": "content is not available",
    },
    {
        "name": "Spotify",
        "url": "https://api.spotify.com/v1/users/{}",
        "errorType": "json_key",
        "errorKey": "error",
    },
    {
        "name": "Behance",
        "url": "https://www.behance.net/{}",
        "errorType": "message",
        "errorMsg": "We couldn't find the page",
    },
    {
        "name": "Dribbble",
        "url": "https://dribbble.com/{}",
        "errorType": "message",
        "errorMsg": "Whoops, that page is gone.",
    },
    {
        "name": "HackerNews",
        "url": "https://news.ycombinator.com/user?id={}",
        "errorType": "message",
        "errorMsg": "No such user.",
    },
    {
        "name": "PyPI",
        "url": "https://pypi.org/pypi/{}/json",
        "errorType": "message",
        "errorMsg": "Not Found",
    },
]